import { describe, it, expect } from 'vitest';
import { getDefaultStartingWeightKg, isBodyweightExercise, isDumbbellExercise } from '@/lib/defaultWeight';
import type { ExerciseCatalogEntry } from '@/types';

function dobForAge(age: number): Date {
  const d = new Date();
  d.setFullYear(d.getFullYear() - age);
  return d;
}

function catalogEntry(overrides: Partial<ExerciseCatalogEntry>): ExerciseCatalogEntry {
  return {
    id: 'catalog-1',
    name: 'Test Exercise',
    aliases: [],
    muscleGroup: 'Test',
    bodyRegion: 'UPPER',
    movementPattern: 'ISOLATION',
    equipment: 'OTHER',
    loadConvention: 'TOTAL',
    progressionType: 'REPS',
    ...overrides,
  };
}

describe('getDefaultStartingWeightKg: matches the approved worked-example table', () => {
  const cases: [age: number, factor: number][] = [
    [18, 0.85],
    [25, 0.95],
    [35, 1.0],
    [45, 0.9],
    [55, 0.8],
    [65, 0.7],
  ];

  it.each(cases)('positive: age %i (factor %s) — male Core on an 80kg bodyweight', (age, factor) => {
    const result = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(age),
      sex: 'MALE',
      muscleGroup: 'Legs',
      bodyweightKg: 80,
    });
    expect(result).toBeCloseTo(80 * 0.8 * factor, 1);
  });

  it.each(cases)('positive: age %i (factor %s) — male Isolation on an 80kg bodyweight', (age, factor) => {
    const result = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(age),
      sex: 'MALE',
      muscleGroup: 'Biceps',
      bodyweightKg: 80,
    });
    expect(result).toBeCloseTo(80 * 0.2 * factor, 1);
  });

  it.each(cases)('positive: age %i (factor %s) — female Core on a 65kg bodyweight', (age, factor) => {
    const result = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(age),
      sex: 'FEMALE',
      muscleGroup: 'Back',
      bodyweightKg: 65,
    });
    expect(result).toBeCloseTo(65 * 0.64 * factor, 1);
  });

  it.each(cases)('positive: age %i (factor %s) — female Isolation on a 65kg bodyweight', (age, factor) => {
    const result = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(age),
      sex: 'FEMALE',
      muscleGroup: 'Triceps',
      bodyweightKg: 65,
    });
    expect(result).toBeCloseTo(65 * 0.16 * factor, 1);
  });
});

describe('getDefaultStartingWeightKg: muscle-group synonyms (free-text field, not an enum)', () => {
  // muscleGroup is typed in freehand via the Plan Builder or generated by the
  // AI chat — neither is constrained to the official seed plans' exact
  // vocabulary ('Quads', 'Core'), so a real plan can easily say "Quadriceps"
  // or "Abs" instead. These must resolve to the same category as their
  // canonical counterpart, not silently fall through to null.
  it.each([
    ['Quadriceps', 'Legs'],
    ['Quad', 'Legs'],
    ['Glute', 'Glutes'],
  ])('positive: "%s" is treated as the same core category as "%s"', (synonym, canonical) => {
    const a = getDefaultStartingWeightKg({ muscleGroup: synonym, bodyweightKg: 80 });
    const b = getDefaultStartingWeightKg({ muscleGroup: canonical, bodyweightKg: 80 });
    expect(a).not.toBeNull();
    expect(a).toBeCloseTo(b!, 5);
  });

  it.each([
    ['Abs', 'Core'],
    ['Abdominals', 'Core'],
    ['Trapezius', 'Biceps'],
    ['Forearms', 'Biceps'],
  ])('positive: "%s" is treated as the same isolation category as "%s"', (synonym, canonical) => {
    const a = getDefaultStartingWeightKg({ muscleGroup: synonym, bodyweightKg: 80 });
    const b = getDefaultStartingWeightKg({ muscleGroup: canonical, bodyweightKg: 80 });
    expect(a).not.toBeNull();
    expect(a).toBeCloseTo(b!, 5);
  });
});

describe('getDefaultStartingWeightKg: negative/edge cases', () => {
  it('negative: no bodyweight logged yet → null, not a bogus 0 or NaN', () => {
    expect(getDefaultStartingWeightKg({ muscleGroup: 'Legs', bodyweightKg: null })).toBeNull();
    expect(getDefaultStartingWeightKg({ muscleGroup: 'Legs', bodyweightKg: 0 })).toBeNull();
  });

  it('negative: an unrecognized/non-lifting muscle group (Cardio, Recovery, Warm-up) → null', () => {
    expect(getDefaultStartingWeightKg({ muscleGroup: 'Cardio', bodyweightKg: 80 })).toBeNull();
    expect(getDefaultStartingWeightKg({ muscleGroup: 'Warm-up', bodyweightKg: 80 })).toBeNull();
    expect(getDefaultStartingWeightKg({ muscleGroup: 'Some Custom Group', bodyweightKg: 80 })).toBeNull();
  });

  it('negative: missing dateOfBirth falls back to the 30-39 baseline (factor 1.0), not a crash', () => {
    const result = getDefaultStartingWeightKg({ sex: 'MALE', muscleGroup: 'Legs', bodyweightKg: 80 });
    expect(result).toBeCloseTo(80 * 0.8 * 1.0, 1);
  });

  it('negative: missing/unspecified sex falls back to the male baseline, not a crash or a female discount applied incorrectly', () => {
    const result = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(35),
      muscleGroup: 'Legs',
      bodyweightKg: 80,
    });
    expect(result).toBeCloseTo(80 * 0.8 * 1.0, 1); // same as explicit MALE, not the -20% female figure
  });
});

describe('getDefaultStartingWeightKg: Beginner plan notches the weight estimate down', () => {
  it('positive: a Beginner plan applies a further -25% on top of the usual estimate', () => {
    const normal = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(35),
      sex: 'MALE',
      muscleGroup: 'Legs',
      bodyweightKg: 80,
    });
    const beginner = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(35),
      sex: 'MALE',
      muscleGroup: 'Legs',
      bodyweightKg: 80,
      planDifficulty: 'Beginner',
    });
    expect(beginner).toBeLessThan(normal!);
    expect(beginner).toBeCloseTo(normal! * 0.75, 5);
  });

  it('positive: matched case-insensitively ("beginner", "BEGINNER")', () => {
    const base = { dateOfBirth: dobForAge(35), sex: 'MALE' as const, muscleGroup: 'Legs', bodyweightKg: 80 };
    const lower = getDefaultStartingWeightKg({ ...base, planDifficulty: 'beginner' });
    const upper = getDefaultStartingWeightKg({ ...base, planDifficulty: 'BEGINNER' });
    const mixed = getDefaultStartingWeightKg({ ...base, planDifficulty: 'Beginner' });
    expect(lower).toBeCloseTo(mixed!, 5);
    expect(upper).toBeCloseTo(mixed!, 5);
  });

  it('negative: Intermediate/Advanced/unset plans are unaffected', () => {
    const base = { dateOfBirth: dobForAge(35), sex: 'MALE' as const, muscleGroup: 'Legs', bodyweightKg: 80 };
    const none = getDefaultStartingWeightKg(base);
    const intermediate = getDefaultStartingWeightKg({ ...base, planDifficulty: 'Intermediate' });
    const advanced = getDefaultStartingWeightKg({ ...base, planDifficulty: 'Advanced' });
    const nullDifficulty = getDefaultStartingWeightKg({ ...base, planDifficulty: null });
    expect(intermediate).toBeCloseTo(none!, 5);
    expect(advanced).toBeCloseTo(none!, 5);
    expect(nullDifficulty).toBeCloseTo(none!, 5);
  });

  it('negative: does not turn a true bodyweight-exercise 0 into something else', () => {
    const result = getDefaultStartingWeightKg({
      muscleGroup: 'Back',
      exerciseName: 'Pull-ups',
      bodyweightKg: 80,
      planDifficulty: 'Beginner',
    });
    expect(result).toBe(0); // 0 * 0.75 is still 0, but this path shouldn't even reach the multiplier
  });

  it('negative: stacks correctly with the female adjustment rather than overriding it', () => {
    const result = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(35),
      sex: 'FEMALE',
      muscleGroup: 'Legs',
      bodyweightKg: 65,
      planDifficulty: 'Beginner',
    });
    expect(result).toBeCloseTo(65 * 0.8 * 0.8 * 0.75, 1);
  });
});

describe('isBodyweightExercise', () => {
  it.each([
    'Pull-up', 'Pull Up', 'Pullups', 'Weighted Pull-ups',
    'Chin-up', 'Chinups',
    'Push-up', 'Pushups',
    'Dips', 'Ring Dips', 'Bench Dips',
    'Muscle-up', 'Muscleups',
    'Inverted Row',
    'TRX / Ring Row', 'TRX Row',
    'Pistol Squat',
  ])('positive: %s is recognized as a bodyweight exercise', (name) => {
    expect(isBodyweightExercise(name)).toBe(true);
  });

  it.each(['Barbell Row', 'Lat Pulldown', 'Bench Press', 'Bicep Curl'])(
    'negative: %s (loaded, not bodyweight) is not flagged',
    (name) => {
      expect(isBodyweightExercise(name)).toBe(false);
    }
  );

  it('negative: no exercise name → false, not a crash', () => {
    expect(isBodyweightExercise(null)).toBe(false);
    expect(isBodyweightExercise(undefined)).toBe(false);
  });
});

describe('getDefaultStartingWeightKg: bodyweight exercises', () => {
  it('positive: Pull-ups (Back, would otherwise get 0.8x bodyweight) suggest 0 added weight instead', () => {
    const result = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(35),
      sex: 'MALE',
      muscleGroup: 'Back',
      exerciseName: 'Pull-ups',
      bodyweightKg: 80,
    });
    expect(result).toBe(0);
  });

  it('positive: bodyweight suggestion applies even without a logged bodyweight — you always start unloaded', () => {
    const result = getDefaultStartingWeightKg({
      muscleGroup: 'Back',
      exerciseName: 'Chin-ups',
      bodyweightKg: null,
    });
    expect(result).toBe(0);
  });

  it('negative: a loaded Back exercise (e.g. Barbell Row) still gets the 0.8x bodyweight estimate', () => {
    const result = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(35),
      sex: 'MALE',
      muscleGroup: 'Back',
      exerciseName: 'Barbell Row',
      bodyweightKg: 80,
    });
    expect(result).toBeCloseTo(80 * 0.8 * 1.0, 1);
  });
});

describe('isDumbbellExercise', () => {
  it.each(['Dumbbell Curl', 'Dumbbell Romanian Deadlift', 'DB Row', 'db bench press', 'Incline Dumbbell Press'])(
    'positive: %s is recognized as a dumbbell exercise',
    (name) => {
      expect(isDumbbellExercise(name)).toBe(true);
    }
  );

  it.each(['Barbell Curl', 'Deadbug', 'Adductor Machine', 'Cable Row', 'Bench Press'])(
    'negative: %s is not flagged (including "db" as a bare substring, e.g. Deadbug)',
    (name) => {
      expect(isDumbbellExercise(name)).toBe(false);
    }
  );

  it('negative: no exercise name → false, not a crash', () => {
    expect(isDumbbellExercise(null)).toBe(false);
    expect(isDumbbellExercise(undefined)).toBe(false);
  });
});

describe('getDefaultStartingWeightKg: dumbbell exercises are halved (per-dumbbell, not combined total)', () => {
  it('positive: a dumbbell exercise gets half the estimate of its barbell/machine equivalent', () => {
    const barbell = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(35),
      sex: 'MALE',
      muscleGroup: 'Biceps',
      exerciseName: 'Barbell Curl',
      bodyweightKg: 80,
    });
    const dumbbell = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(35),
      sex: 'MALE',
      muscleGroup: 'Biceps',
      exerciseName: 'Dumbbell Curl',
      bodyweightKg: 80,
    });
    expect(dumbbell).toBeCloseTo(barbell! * 0.5, 5);
  });

  it('negative: stacks correctly with Beginner + female adjustments rather than overriding them', () => {
    const result = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(35),
      sex: 'FEMALE',
      muscleGroup: 'Biceps',
      exerciseName: 'Dumbbell Curl',
      bodyweightKg: 65,
      planDifficulty: 'Beginner',
    });
    expect(result).toBeCloseTo(65 * 0.2 * 0.8 * 0.75 * 0.5, 1);
  });

  it('negative: a true bodyweight dumbbell-named edge case still short-circuits to 0 (bodyweight check runs first)', () => {
    // Not a realistic exercise name, just confirms precedence: bodyweight
    // detection short-circuits before the dumbbell halving is ever applied.
    const result = getDefaultStartingWeightKg({
      muscleGroup: 'Back',
      exerciseName: 'Dumbbell Pull-up',
      bodyweightKg: 80,
    });
    expect(result).toBe(0);
  });
});

describe('isDumbbellExercise: catalog match takes precedence over the name keyword guess', () => {
  it('positive: a catalog PER_SIDE dumbbell entry is flagged even if the name has no "dumbbell"/"DB" in it', () => {
    const entry = catalogEntry({ equipment: 'DUMBBELL', loadConvention: 'PER_SIDE' });
    expect(isDumbbellExercise('Bicep Curl', entry)).toBe(true);
  });

  it('negative: fixes the false positive the name-only check couldn\'t avoid — a "Dumbbell Swing"/"Kettlebell Swing" uses ONE implement held two-handed, not one per side', () => {
    const entry = catalogEntry({ equipment: 'DUMBBELL', loadConvention: 'TOTAL' });
    // Name-only check would say true (contains "Dumbbell"); the catalog knows better.
    expect(isDumbbellExercise('Dumbbell Swing', entry)).toBe(false);
    expect(isDumbbellExercise('Dumbbell Swing')).toBe(true); // without a catalog match, still the old (wrong-for-this-case) guess
  });

  it('negative: a kettlebell (not dumbbell) catalog entry is never flagged, even if PER_SIDE', () => {
    const entry = catalogEntry({ equipment: 'KETTLEBELL', loadConvention: 'PER_SIDE' });
    expect(isDumbbellExercise('Double Kettlebell Front Squat', entry)).toBe(false);
  });
});

describe('isBodyweightExercise: catalog match takes precedence over the name keyword guess', () => {
  it('positive: BODYWEIGHT_LOADABLE catalog entries count as bodyweight (weighted pull-up/dip starting point is still 0)', () => {
    const entry = catalogEntry({ loadConvention: 'BODYWEIGHT_LOADABLE' });
    expect(isBodyweightExercise('Weighted Chin-up', entry)).toBe(true);
  });

  it('negative: a catalog entry that is NOT bodyweight overrides a name that would otherwise keyword-match', () => {
    // "Dip Machine Press" contains "dip", which the name-only keyword list would flag —
    // the catalog says this particular row is a loaded machine movement instead.
    const entry = catalogEntry({ loadConvention: 'TOTAL', equipment: 'MACHINE' });
    expect(isBodyweightExercise('Dip Machine Press', entry)).toBe(false);
  });
});

describe('getDefaultStartingWeightKg: catalog movementPattern overrides the muscleGroup keyword guess', () => {
  it('positive: uses the catalog\'s movementPattern even when the logged muscleGroup would resolve differently', () => {
    // muscleGroup says "Cardio" (normally → null, no estimate) but the
    // catalog knows this specific exercise is really a compound lift.
    const entry = catalogEntry({ movementPattern: 'COMPOUND' });
    const result = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(35),
      sex: 'MALE',
      muscleGroup: 'Cardio',
      exerciseName: 'Something Miscategorized',
      bodyweightKg: 80,
      catalogEntry: entry,
    });
    expect(result).toBeCloseTo(80 * 0.8 * 1.0, 1); // 'core' (compound) multiplier, not null
  });

  it('positive: still produces an estimate when muscleGroup is missing entirely, as long as there\'s a catalog match', () => {
    const entry = catalogEntry({ movementPattern: 'ISOLATION' });
    const result = getDefaultStartingWeightKg({
      dateOfBirth: dobForAge(35),
      sex: 'MALE',
      muscleGroup: null,
      exerciseName: 'Something With No Logged Muscle Group',
      bodyweightKg: 80,
      catalogEntry: entry,
    });
    expect(result).toBeCloseTo(80 * 0.2 * 1.0, 1);
  });
});
